table hora_inicio_fin
	lineageTag: 51ba3187-7ccf-4af6-ba08-49c3373cee82

	/// Total global de horas extras en formato HH:MM:SS. Calculado desde la columna Minutos Extra. Usar en tarjetas KPI de resumen general.
	measure 'Total Minutos Extra HHMMSS' = ```
			
			VAR TotalSegundos =
			    SUMX(
			        'hora_inicio_fin',
			        HOUR('hora_inicio_fin'[Minutos Extra]) * 3600 +
			        MINUTE('hora_inicio_fin'[Minutos Extra]) * 60 
			    )
			
			VAR Horas = INT(TotalSegundos / 3600)
			VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)
			
			RETURN
			FORMAT(Horas,"00") & ":" &
			FORMAT(Minutos,"00") 
			```
		displayFolder: Totales y Formato
		lineageTag: 4f649887-f795-4f34-936c-696c09aaef8d

	/// Cuenta el número de registros con hora de inicio registrada. Útil para medir la cantidad de actividades en un período, independiente de las horas extras.
	measure 'Conteo inicio' = COUNT(hora_inicio_fin[hora_inicio])
		formatString: 0
		displayFolder: Picos y Patrones
		lineageTag: a971f4cc-eae2-4417-822a-c927efaf048c

	/// Hora del día (HH:MM) con mayor concentración de registros de inicio de actividad. Identifica el horario más frecuente de inicio de trabajo extra.
	measure 'Hora Pico Inicio' = ```
			
			VAR TablaHoras =
			    SUMMARIZE(
			        ALL('hora_inicio_fin'[hora_inicio]),
			        'hora_inicio_fin'[hora_inicio],
			        "Eventos", COUNT('hora_inicio_fin'[hora_inicio])
			    )
			VAR MaxEventos =
			    MAXX(TablaHoras, [Eventos])
			RETURN
			MAXX(
			    FILTER(TablaHoras, [Eventos] = MaxEventos),
			    FORMAT('hora_inicio_fin'[hora_inicio], "hh:mm")
			)
			
			```
		displayFolder: Picos y Patrones
		lineageTag: 4322d4d1-e037-4ec3-be62-c3550fc7af65

	/// Día de la semana con más registros de hora de inicio. Permite identificar qué día concentra mayor actividad extra.
	measure 'Día Pico Inicio' =
			
			VAR TablaDias =
			    SUMMARIZE(
			        ALL('Calendario'[DiaSemana]),
			        'Calendario'[DiaSemana],
			        "Horas", COUNT('hora_inicio_fin'[hora_inicio])
			    )
			VAR MaxHoras =
			    MAXX(TablaDias, [Horas])
			RETURN
			MAXX(
			    FILTER(TablaDias, [Horas] = MaxHoras),
			    'Calendario'[DiaSemana]
			)
		displayFolder: Picos y Patrones
		lineageTag: 8273590a-e673-4cc0-8f33-5f0409430819

	/// Subtotal de horas extras al 50% en formato HH:MM:SS. Filtra registros donde Hora = 'Hora al 50%'. Complemento de la medida al 100%.
	measure 'Total Minutos Extra HHMMSS 50%' =
			
			VAR TotalSegundos =
			    SUMX(
			        FILTER(
			            'hora_inicio_fin',
			            'hora_inicio_fin'[Hora] = "Hora al 50%"
			        ),
			        HOUR('hora_inicio_fin'[Minutos Extra]) * 3600 +
			        MINUTE('hora_inicio_fin'[Minutos Extra]) * 60 +
			        SECOND('hora_inicio_fin'[Minutos Extra])
			    )
			
			VAR Horas = INT(TotalSegundos / 3600)
			VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)
			VAR Segundos = INT(MOD(TotalSegundos, 60))
			
			RETURN
			FORMAT(Horas,"00") & ":" &
			FORMAT(Minutos,"00") & ":" &
			FORMAT(Segundos,"00")
		displayFolder: Totales y Formato
		lineageTag: 6ca5b4f9-ba5f-458f-93d1-cec7d1a6a3fc

	/// Subtotal de horas extras al 100% en formato HH:MM:SS. Filtra registros donde Hora = 'Hora al 100%'. Aplica a feriados y turnos nocturnos.
	measure 'Total Minutos Extra HHMMSS 100%' =
			
			VAR TotalSegundos =
			    SUMX(
			        FILTER(
			            'hora_inicio_fin',
			            'hora_inicio_fin'[Hora] = "Hora al 100%"
			        ),
			        HOUR('hora_inicio_fin'[Minutos Extra]) * 3600 +
			        MINUTE('hora_inicio_fin'[Minutos Extra]) * 60 +
			        SECOND('hora_inicio_fin'[Minutos Extra])
			    )
			
			VAR Horas = INT(TotalSegundos / 3600)
			VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)
			VAR Segundos = INT(MOD(TotalSegundos, 60))
			
			RETURN
			FORMAT(Horas,"00") & ":" &
			FORMAT(Minutos,"00") & ":" &
			FORMAT(Segundos,"00")
		displayFolder: Totales y Formato
		lineageTag: 8a2ca405-f32d-460d-83fe-c5764afd9dd2

	/// Nombre del mes con mayor acumulado de MinutosExtraTotales. Considera todos los meses disponibles ignorando filtros de fecha. Ideal para tarjeta KPI.
	measure 'Mes Pico Extra' =
			
			VAR TablaMeses =
			    SUMMARIZE(
			        ALL('Calendario'[Mes]),
			        'Calendario'[Mes],
			        "Horas", SUM('hora_inicio_fin'[MinutosExtraTotales])
			    )
			RETURN
			MAXX(
			    FILTER(TablaMeses, [Horas] = MAXX(TablaMeses, [Horas])),
			    'Calendario'[Mes]
			)
		displayFolder: Picos y Patrones
		lineageTag: b7aaaedc-7367-4862-b639-780ecb3259c7

	/// Total de horas extras del mes pico en formato HH:MM. Complementa la medida Mes Pico Extra para mostrar la magnitud del pico.
	measure 'Hora Mes Pico Extra' = ```
			
			VAR TablaMeses =
			    SUMMARIZE(
			        ALL('Calendario'[Mes]),
			        'Calendario'[Mes],
			        "MinutosMes", SUM('hora_inicio_fin'[MinutosExtraTotales])
			    )
			
			VAR MaxMinutos =
			    MAXX(TablaMeses, [MinutosMes])
			
			VAR TotalSegundos = MaxMinutos * 60
			
			VAR Horas = INT(TotalSegundos / 3600)
			VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)
			VAR Segundos = INT(MOD(TotalSegundos, 60))
			
			RETURN
			FORMAT(Horas,"00") & ":" &
			FORMAT(Minutos,"00") 
			```
		displayFolder: Picos y Patrones
		lineageTag: c37ae219-7f87-44b4-9e6e-cfab9ef32131

	/// Texto combinado: nombre del mes pico + total de horas entre paréntesis. Ejemplo: 'Marzo (127)'. Listo para usar en una tarjeta KPI de texto.
	measure 'KPI Mes Pico Extra' =
			
			VAR Mes = [Mes Pico Extra]
			VAR Horas = [Hora Mes Pico Extra]
			RETURN
			Mes & " (" & FORMAT(Horas, "#,##0") & ")"
		displayFolder: Picos y Patrones
		lineageTag: ed278efc-6b9b-4568-b401-d844c7f59cb6

	/// Nombre de la empresa (fichasgest_cliente) con mayor acumulado de horas extras. Usa la relación cliente_id para obtener el nombre desde la tabla de clientes.
	measure 'Cliente Pico Extra' =
			
			VAR TablaClientes =
			    SUMMARIZE(
			        ALL('hora_inicio_fin'[cliente_id]),
			        'hora_inicio_fin'[cliente_id],
			        "MinutosCliente", SUM('hora_inicio_fin'[MinutosExtraTotales])
			    )
			
			VAR MaxMinutos =
			    MAXX(TablaClientes, [MinutosCliente])
			
			VAR ClienteTop =
			    MAXX(
			        FILTER(TablaClientes, [MinutosCliente] = MaxMinutos),
			        'hora_inicio_fin'[cliente_id]
			    )
			
			RETURN
			CALCULATE(
			    SELECTEDVALUE('fichasgest_cliente'[empresa]),
			    'fichasgest_cliente'[id] = ClienteTop
			)
		displayFolder: Clientes
		lineageTag: 0eb8d9a1-e937-47cb-9e33-ab8e7324b6f8

	/// Total de horas extras del cliente con mayor acumulado, en formato HH:MM. Complementa la medida Cliente Pico Extra para mostrar la magnitud.
	measure 'Hora Cliente Pico Extra' =
			
			VAR TablaMeses =
			    SUMMARIZE(
			        ALL(hora_inicio_fin[cliente_id]),
			        hora_inicio_fin[cliente_id],
			        "MinutosMes", SUM('hora_inicio_fin'[MinutosExtraTotales])
			    )
			
			VAR MaxMinutos =
			    MAXX(TablaMeses, [MinutosMes])
			
			VAR TotalSegundos = MaxMinutos * 60
			
			VAR Horas = INT(TotalSegundos / 3600)
			VAR Minutos = INT(MOD(TotalSegundos, 3600) / 60)
			VAR Segundos = INT(MOD(TotalSegundos, 60))
			
			RETURN
			FORMAT(Horas,"00") & ":" &
			FORMAT(Minutos,"00")
		displayFolder: Clientes
		lineageTag: efb4d8e6-6d23-44c2-9d1c-3baba4e1a02c

	/// Texto combinado: nombre del cliente pico + total de horas entre paréntesis. Listo para tarjeta KPI de texto. Ejemplo: 'Empresa ABC (98)'.
	measure 'KPI Cliente Pico Extra' =
			
			VAR Mes = [Cliente Pico Extra]
			VAR Horas = [Hora Cliente Pico Extra]
			RETURN
			Mes & " (" & FORMAT(Horas, "#,##0") & ")"
		displayFolder: Clientes
		lineageTag: b4438fe4-af7e-4b3a-a4b1-3ca473ccd856

	/// Total de horas extras en formato H:MM. Suma MinutosExtraTotales y convierte a horas y minutos. Usar en tablas y tarjetas de resumen.
	measure HorasExtra_h_mm = ```
			
			VAR TotalMinutos =
			    COALESCE(
			        SUM ( 'hora_inicio_fin'[MinutosExtraTotales] ),
			        0
			    )
			VAR Horas =
			    INT ( TotalMinutos / 60 )
			VAR Minutos =
			    MOD ( TotalMinutos, 60 )
			RETURN
			    FORMAT ( Horas, "0" ) & ":" & FORMAT ( Minutos, "00" )
			
			
			```
		displayFolder: Totales y Formato
		lineageTag: bc0250e3-5f3d-43ec-8a4b-8abc3627f8a0

	/// Clasifica un registro como 'Hora al 100%' si el tipo de jornada es Extra o Feriado, o si tiene Extra Temprano con duración válida. Usada como columna calculada de apoyo.
	measure 'Hora 100' =
			
			VAR TipoExtra = SELECTEDVALUE(hora_inicio_fin[Extra])
			
			VAR ExtraTempranoInicio = SELECTEDVALUE(hora_inicio_fin[Extra Temprano Inicio])
			VAR ExtraTempranoFinRaw = SELECTEDVALUE(hora_inicio_fin[Extra Temprano Fin])
			
			VAR ExtraTempranoFin =
			    IF(
			        NOT ISBLANK(ExtraTempranoInicio)
			        && ExtraTempranoFinRaw < ExtraTempranoInicio,
			        ExtraTempranoFinRaw + 1,
			        ExtraTempranoFinRaw
			    )
			
			VAR Hay100 =
			    NOT ISBLANK(ExtraTempranoInicio)
			    && NOT ISBLANK(ExtraTempranoFin)
			    && ExtraTempranoFin > ExtraTempranoInicio
			
			RETURN
			IF(
			    TipoExtra IN {"Extra","Feriado"} || Hay100,
			    "Hora al 100%",
			    ""
			)
		displayFolder: Clasificación de Horas
		lineageTag: d3ff136c-bfc4-4b04-85ba-fbc3f52a9290

	/// Clasifica un registro como 'Hora al 50%' si tiene Extra Tarde con duración válida y no es jornada Extra o Feriado. Usada como columna calculada de apoyo en tablas de detalle.
	measure 'Hora 50' =
			
			VAR TipoExtra = SELECTEDVALUE(hora_inicio_fin[Extra])
			
			VAR ExtraTardeInicio = SELECTEDVALUE(hora_inicio_fin[Extra Tarde Inicio])
			VAR ExtraTardeFinRaw = SELECTEDVALUE(hora_inicio_fin[Extra Tarde Fin])
			
			VAR ExtraTardeFin =
			    IF(
			        NOT ISBLANK(ExtraTardeInicio)
			        && ExtraTardeFinRaw < ExtraTardeInicio,
			        ExtraTardeFinRaw + 1,
			        ExtraTardeFinRaw
			    )
			
			VAR Hay50 =
			    NOT ISBLANK(ExtraTardeInicio)
			    && NOT ISBLANK(ExtraTardeFin)
			    && ExtraTardeFin > ExtraTardeInicio
			
			RETURN
			IF(
			    NOT(TipoExtra IN {"Extra","Feriado"}) && Hay50,
			    "Hora al 50%",
			    ""
			)
		displayFolder: Clasificación de Horas
		lineageTag: 72f39a12-e123-425f-aed1-ba8bd64c617e

	/// Total de horas extras al 50% en formato HH:MM. Basado en columna Minutos50. Usar junto a HorasExtra100_h_mm para desglosar el tipo de recargo.
	measure HorasExtra50_h_mm = ```
			
			VAR TotalMinutos =
			    COALESCE(
			        ROUND(SUM('hora_inicio_fin'[Minutos50]),0),
			        0
			    )
			VAR Horas =
			    INT(TotalMinutos / 60)
			VAR Minutos =
			    MOD(TotalMinutos, 60)
			
			RETURN
			FORMAT(Horas,"00") & ":" & FORMAT(Minutos,"00") 
			```
		displayFolder: Totales y Formato
		lineageTag: b9551df0-6070-4ce2-8d4a-8f07ad49c9cc

	/// Total de horas extras al 100% en formato HH:MM. Basado en columna Minutos100. Aplica a jornadas en feriados o turnos nocturnos.
	measure HorasExtra100_h_mm = ```
			
			VAR TotalMinutos =
			    COALESCE(
			        ROUND(SUM('hora_inicio_fin'[Minutos100]),0),
			        0
			    )
			VAR Horas =
			    INT(TotalMinutos / 60)
			VAR Minutos =
			    MOD(TotalMinutos, 60)
			
			RETURN
			FORMAT(Horas,"00") & ":" & FORMAT(Minutos,"00") 
			```
		displayFolder: Totales y Formato
		lineageTag: 9bf14c98-c390-4270-a1f3-f8edfd29da49

	/// Posición del consultor por total de minutos extra (1 = más horas). Muestra BLANK en la fila de totales. Usa auth_user[Consultor] via ingeniero_id.
	measure 'Ranking Consultor Horas Extra' =
			IF(
			    ISINSCOPE( auth_user[Consultor] ),
			    RANKX(
			        ALLSELECTED( auth_user[Consultor] ),
			        CALCULATE(
			            COALESCE( SUM( hora_inicio_fin[MinutosExtraTotales] ), 0 )
			        ),
			        ,
			        DESC,
			        DENSE
			    ),
			    BLANK()
			)
		formatString: 0
		displayFolder: Análisis Horas Extra
		lineageTag: 9b6f80da-d787-487b-ad11-f9bdf8c5227b

	/// Nombre del consultor con mayor acumulado de horas extras en el período filtrado. Ideal para tarjeta KPI. Usa auth_user[Consultor] via ingeniero_id.
	measure 'Top Consultor Horas Extra' =
			VAR Resumen =
			    ADDCOLUMNS(
			        ALLSELECTED( auth_user[Consultor] ),
			        "TotalMin",
			        CALCULATE(
			            COALESCE( SUM( hora_inicio_fin[MinutosExtraTotales] ), 0 )
			        )
			    )
			VAR MaxMin = MAXX( Resumen, [TotalMin] )
			RETURN
			    MINX(
			        FILTER( Resumen, [TotalMin] = MaxMin ),
			        auth_user[Consultor]
			    )
		displayFolder: Análisis Horas Extra
		lineageTag: 3a9b9d46-05d8-48d9-8a77-1dae9e1f5c73

	/// Porcentaje de horas extras de cada consultor sobre el total del período seleccionado. Usa auth_user[Consultor] vía ingeniero_id.
	measure '% Horas Extra del Total' =
			VAR TotalConsultor =
			    COALESCE( SUM( hora_inicio_fin[MinutosExtraTotales] ), 0 )
			VAR TotalGeneral =
			    CALCULATE(
			        COALESCE( SUM( hora_inicio_fin[MinutosExtraTotales] ), 0 ),
			        ALLSELECTED( auth_user[Consultor] )
			    )
			RETURN
			    DIVIDE( TotalConsultor, TotalGeneral, 0 )
		formatString: 0.00%
		displayFolder: Análisis Horas Extra
		lineageTag: bdddf431-690f-4f40-8e80-63ceb5565fe7

	/// Total de horas extras al 50% en valor decimal. Usar como valor numérico en gráficos (eje Y, barras apiladas). Complemento de Horas Extra 100 (h).
	measure 'Horas Extra 50 (h)' = DIVIDE( COALESCE( SUM( hora_inicio_fin[Minutos50] ), 0 ), 60 )
		formatString: 0.0
		displayFolder: Totales y Formato
		lineageTag: db1f4e11-f5e2-4079-a7a8-415c561120aa

	/// Total de horas extras al 100% en valor decimal. Usar como valor numérico en gráficos (eje Y, barras apiladas). Complemento de Horas Extra 50 (h).
	measure 'Horas Extra 100 (h)' = DIVIDE( COALESCE( SUM( hora_inicio_fin[Minutos100] ), 0 ), 60 )
		formatString: 0.0
		displayFolder: Totales y Formato
		lineageTag: e04435a6-420c-4555-9335-34ddebac64e9

	/// Etiqueta de datos en formato H:MM para el segmento de horas al 50%. Devuelve BLANK cuando es 0 para no mostrar etiquetas vacías en el gráfico. Usar en el campo Etiquetas de datos del visual de barras apiladas.
	measure 'Etiqueta Horas 50 (h:mm)' =
			VAR TotalMinutos = COALESCE( ROUND( SUM( hora_inicio_fin[Minutos50] ), 0 ), 0 )
			VAR Horas = INT( TotalMinutos / 60 )
			VAR Minutos = MOD( TotalMinutos, 60 )
			RETURN
			IF(
			    TotalMinutos = 0,
			    BLANK(),
			    FORMAT( Horas, "0" ) & ":" & FORMAT( Minutos, "00" )
			)
		displayFolder: Totales y Formato
		lineageTag: 3078961a-61a7-49dc-9f85-571ccb53536b

	/// Etiqueta de datos en formato H:MM para el segmento de horas al 100%. Devuelve BLANK cuando es 0 para no mostrar etiquetas vacías en el gráfico. Usar en el campo Etiquetas de datos del visual de barras apiladas.
	measure 'Etiqueta Horas 100 (h:mm)' =
			VAR TotalMinutos = COALESCE( ROUND( SUM( hora_inicio_fin[Minutos100] ), 0 ), 0 )
			VAR Horas = INT( TotalMinutos / 60 )
			VAR Minutos = MOD( TotalMinutos, 60 )
			RETURN
			IF(
			    TotalMinutos = 0,
			    BLANK(),
			    FORMAT( Horas, "0" ) & ":" & FORMAT( Minutos, "00" )
			)
		displayFolder: Totales y Formato
		lineageTag: c81c69c5-a915-4f55-8032-25e7d2ae28aa

	/// Etiqueta del total apilado en formato H:MM (50% + 100% combinados). Devuelve BLANK cuando es 0. Usar como etiqueta del total de la pila en el gráfico de barras apiladas.
	measure 'Etiqueta Total Horas Extra (h:mm)' =
			VAR TotalMinutos = COALESCE( ROUND( SUM( hora_inicio_fin[MinutosExtraTotales] ), 0 ), 0 )
			VAR Horas = INT( TotalMinutos / 60 )
			VAR Minutos = MOD( TotalMinutos, 60 )
			RETURN
			IF(
			    TotalMinutos = 0,
			    BLANK(),
			    FORMAT( Horas, "0" ) & ":" & FORMAT( Minutos, "00" )
			)
		displayFolder: Totales y Formato
		lineageTag: eb641dc1-e87d-4d4b-9571-d7500a18040f

	/// Fecha y hora de la actividad. Clave de relación con Calendario[Fecha] a través de FechaC.
	column fecha_actividad
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7267fe92-41f3-4abc-b2b3-8eedb5900205
		summarizeBy: none
		sourceColumn: fecha_actividad

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Clave foránea hacia fichasgest_cliente. Cliente al que corresponde el registro de hora.
	column cliente_id
		dataType: int64
		formatString: 0
		lineageTag: 569c4a93-6be5-4ade-a207-d89929eac99c
		summarizeBy: none
		sourceColumn: cliente_id

		annotation SummarizationSetBy = Automatic

	/// Clave foránea hacia auth_user. Ingeniero o consultor que realizó la actividad.
	column ingeniero_id
		dataType: int64
		formatString: 0
		lineageTag: 88c93535-e0ec-487f-a019-dffe0b7cd1d3
		summarizeBy: none
		sourceColumn: ingeniero_id

		annotation SummarizationSetBy = Automatic

	/// Hora de inicio de la actividad registrada.
	column hora_inicio
		dataType: dateTime
		formatString: h:nn:ss
		lineageTag: a9004575-5980-4571-acdd-e8010bcbe1b0
		summarizeBy: none
		sourceColumn: hora_inicio

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	/// Hora de fin de la actividad registrada.
	column hora_fin
		dataType: dateTime
		formatString: h:nn:ss
		lineageTag: 2cdb3a01-5bc7-4950-8523-72844bb8adb8
		summarizeBy: none
		sourceColumn: hora_fin

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	/// Fecha de la actividad truncada al día (sin hora). Usada para relacionar con Calendario[Fecha].
	column FechaC = DATEVALUE('hora_inicio_fin'[fecha_actividad])
		formatString: General Date
		lineageTag: ade184f0-6a87-4ef6-8d44-4c47fc3d2c89
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Identificador único del registro de hora inicio-fin.
	column id_unico
		dataType: int64
		formatString: 0
		lineageTag: d7a4a295-3a1b-4f90-8d26-3d172b6a7c5c
		summarizeBy: sum
		sourceColumn: id_unico

		annotation SummarizationSetBy = Automatic

	/// Duración total del registro calculada como hora_fin - hora_inicio. Base para determinar si la jornada supera el límite ordinario.
	column Duracion =
			
			MOD(
			    'hora_inicio_fin'[hora_fin] - 'hora_inicio_fin'[hora_inicio],
			    1
			)
		dataType: dateTime
		formatString: Long Time
		displayFolder: Totales y Formato
		lineageTag: 3611e9ea-9bb9-4517-9f81-d479bb62dafa
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	/// Clasifica cada registro como 'Normal', 'Extra' o 'Feriado' según el tipo de jornada. Usa Calendario[DiaSemanaNum] vía RELATED (6=Sábado, 7=Domingo) en lugar de nombre_dia para mayor robustez. Columna de segmentación clave para filtrar horas extras en visuals.
	column Extra =
			VAR DiaSemana = RELATED( Calendario[DiaSemanaNum] )
			VAR EsFeriado = RELATED( Calendario[EsFeriado] ) = 1
			RETURN
			SWITCH(
			    TRUE(),
			    EsFeriado, "Feriado",
			    DiaSemana IN { 6, 7 }, "Extra",
			    "Normal"
			)
		displayFolder: Clasificación de Horas
		lineageTag: 31dabf7d-4b19-49f0-8121-e22c9422aec1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Minutos del registro que corresponden a jornada ordinaria. Complemento de Minutos Extra para obtener el total de la actividad.
	column 'Minutos Normales' =
			
			VAR EsExtraDia =
			    'hora_inicio_fin'[Extra] IN {"Extra","Feriado"}
			VAR Inicio =
			    TIME(
			        HOUR('hora_inicio_fin'[hora_inicio]),
			        MINUTE('hora_inicio_fin'[hora_inicio]),
			        SECOND('hora_inicio_fin'[hora_inicio])
			    )
			
			VAR Fin =
			    TIME(
			        HOUR('hora_inicio_fin'[hora_fin]),
			        MINUTE('hora_inicio_fin'[hora_fin]),
			        SECOND('hora_inicio_fin'[hora_fin])
			    )
			
			VAR InicioLab = TIME(9,0,0)
			VAR FinLab    = TIME(18,0,0)
			
			VAR InicioEfectivo = MAX(Inicio, InicioLab)
			VAR FinEfectivo    = MIN(Fin, FinLab)
			
			VAR DuracionNormal =
			    IF(
			        FinEfectivo > InicioEfectivo,
			        FinEfectivo - InicioEfectivo,
			        0
			    )
			
			RETURN
			IF(
			    EsExtraDia,
			    0,
			    DuracionNormal
			)
		dataType: dateTime
		formatString: Long Time
		displayFolder: Totales y Formato
		lineageTag: deaebeeb-9765-49e6-bd52-aff9b074b19d
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	/// Minutos fuera de la jornada ordinaria en formato DateTime. Usado como base para calcular MinutosExtraTotales y HorasExtraFormato.
	column 'Minutos Extra' =
			
			'hora_inicio_fin'[Duracion]
			-
			'hora_inicio_fin'[Minutos Normales]
		formatString: Long Time
		displayFolder: Totales y Formato
		lineageTag: da504af1-7acf-4c3e-a6a5-d240d8d33415
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	/// Total de minutos extra en valor numérico decimal. Columna base sobre la que se construyen todas las medidas de horas extras del modelo.
	column MinutosExtraTotales = (HOUR([Minutos Extra]) * 60 + MINUTE([Minutos Extra]) + SECOND([Minutos Extra])/60)
		displayFolder: Totales y Formato
		lineageTag: dfa3322b-effb-4273-99f1-01ec497ad678
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Horas extras del registro en texto con formato HH:MM. Útil para mostrar el detalle por fila en tablas de detalle sin necesidad de una medida.
	column HorasExtraFormato =
			
			VAR TotalMin = [MinutosExtraTotales]
			VAR H = INT(TotalMin / 60)
			VAR M = MOD(TotalMin, 60)
			RETURN
			FORMAT(H, "00") & ":" & FORMAT(M, "00")
		displayFolder: Totales y Formato
		lineageTag: 1c1bccab-1b98-4e4c-921e-117e2fdd7589
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Hora de inicio del tramo extra temprano (antes del horario ordinario). Se usa para calcular las horas al 100% en jornadas que comienzan antes del límite.
	column 'Extra Temprano Inicio' =
			
			VAR InicioTrabajo = 'hora_inicio_fin'[hora_inicio]
			VAR InicioNormal  = TIME(9,0,0)
			VAR EsExtra       = 'hora_inicio_fin'[Extra] IN {"Extra","Feriado"}
			
			RETURN
			IF(
			    EsExtra
			        || InicioTrabajo < InicioNormal,
			    InicioTrabajo,
			    BLANK()
			)
		formatString: Long Time
		displayFolder: Franjas Horarias
		lineageTag: cfeb3db6-014b-4a85-940b-2a48aa183e47
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	/// Hora de fin del tramo extra temprano. Junto con Extra Temprano Inicio determina la duración del tramo nocturno o anticipado con recargo al 100%.
	column 'Extra Temprano Fin' =
			
			VAR InicioTrabajo = 'hora_inicio_fin'[hora_inicio]
			VAR FinTrabajo    = 'hora_inicio_fin'[hora_fin]
			VAR TipoExtra     = 'hora_inicio_fin'[Extra]
			VAR InicioNormal  = TIME(9,0,0)
			
			RETURN
			IF(
			    TipoExtra IN {"Extra","Feriado"},
			        -- Si es Extra manual, siempre se toma el fin tal cual
			        FinTrabajo,
			    -- Si es Normal, se aplica la regla contra las 09:00
			    IF(
			        InicioTrabajo < InicioNormal,
			        MIN(FinTrabajo, InicioNormal),
			        BLANK()
			    )
			)
		formatString: Long Time
		displayFolder: Franjas Horarias
		lineageTag: 2750fc8d-9389-4fd7-83ad-fd6e6c9935f2
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	/// Hora de inicio del tramo extra tarde (después del horario ordinario). Base del cálculo de horas al 50% en jornadas que se extienden fuera del horario normal.
	column 'Extra Tarde Inicio' =
			
			VAR InicioTrabajo = 'hora_inicio_fin'[hora_inicio]
			VAR TipoExtra = 'hora_inicio_fin'[Extra]
			VAR FinTrabajo =
			    IF(
			        'hora_inicio_fin'[hora_fin] < InicioTrabajo,
			        'hora_inicio_fin'[hora_fin] + 1,
			        'hora_inicio_fin'[hora_fin]
			    )
			
			VAR FinNormal = TIME(18,0,0)
			
			RETURN
			IF(
			    TipoExtra = "Extra",
			        -- Si es Extra manual, siempre se toma el fin tal cual
			        BLANK(),
			    -- Si es Normal, se aplica la regla contra las 09:00
			    IF(
			    FinTrabajo > FinNormal,
			    MAX(InicioTrabajo, FinNormal),
			    BLANK()
			    )
			)
		formatString: Long Time
		displayFolder: Franjas Horarias
		lineageTag: f237054a-3b01-43a4-b858-1d0f7256555e
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	/// Hora de fin del tramo extra tarde. Junto con Extra Tarde Inicio determina la duración del tramo vespertino con recargo al 50%.
	column 'Extra Tarde Fin' =
			
			VAR InicioTrabajo = 'hora_inicio_fin'[hora_inicio]
			VAR TipoExtra = 'hora_inicio_fin'[Extra]
			VAR FinTrabajo =
			    IF(
			        'hora_inicio_fin'[hora_fin] < InicioTrabajo,
			        'hora_inicio_fin'[hora_fin] + 1,
			        'hora_inicio_fin'[hora_fin]
			    )
			
			VAR FinNormal = TIME(18,0,0)
			
			RETURN
			IF(
			     TipoExtra = "Extra",
			        -- Si es Extra manual, siempre se toma el fin tal cual
			        BLANK(),
			        if(
			    FinTrabajo > FinNormal,
			    FinTrabajo,
			    BLANK())
			)
		formatString: Long Time
		displayFolder: Franjas Horarias
		lineageTag: 8fee07e0-f3a3-4902-9b7d-98bf3e0915b2
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	/// Clasifica el registro como 'Hora al 50%' o 'Hora al 100%' según el tramo horario. Usada como filtro en las medidas Total Minutos Extra HHMMSS 50% y 100%.
	column Hora = ```
			
			VAR TipoExtra = 'hora_inicio_fin'[Extra]
			
			VAR ExtraTardeInicio = hora_inicio_fin[Extra Tarde Inicio]
			VAR ExtraTardeFinRaw = hora_inicio_fin[Extra Tarde Fin]
			
			VAR ExtraTardeFin =
			    IF(
			        NOT ISBLANK(ExtraTardeInicio)
			            && ExtraTardeFinRaw < ExtraTardeInicio,
			        ExtraTardeFinRaw + 1,
			        ExtraTardeFinRaw
			    )
			VAR ExtraTempranoInicio = hora_inicio_fin[Extra Temprano Inicio]
			VAR ExtraTempranoFinRaw = hora_inicio_fin[Extra Temprano Fin]
			
			VAR ExtraTempranoFin =
			    IF(
			        NOT ISBLANK(ExtraTempranoInicio)
			            && ExtraTempranoFinRaw < ExtraTempranoInicio,
			        ExtraTempranoFinRaw + 1,
			        ExtraTempranoFinRaw
			    )
			
			
			VAR Hay50 =
			    NOT ISBLANK(ExtraTardeInicio)
			        && NOT ISBLANK(ExtraTardeFin)
			        && ExtraTardeFin > ExtraTardeInicio
			VAR Hay100 =
			    NOT ISBLANK(ExtraTempranoInicio)
			        && NOT ISBLANK(ExtraTempranoFin)
			        && ExtraTempranoFin > ExtraTempranoInicio
			
			
			RETURN
			SWITCH(
			    TRUE(),
			
			    -- 🔴 PRIORIDAD 1: Si es Extra manual
			    TipoExtra IN {"Extra","Feriado"}, "Hora al 100%",
			
			    -- 🟡 Evaluación normal,
			    Hay100, "Hora al 100%",
			    Hay50, "Hora al 50%",    
			    
			
			
			    ""
			)
			```
		displayFolder: Clasificación de Horas
		lineageTag: 46d2c2b5-8194-4399-b43c-b67d88ddfe1c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Minutos extra con recargo al 50%, correspondientes al tramo Extra Tarde (fuera de horario pero en jornada normal). Base de las medidas HorasExtra50_h_mm.
	column Minutos50 =
			
			VAR Inicio =
			    TIME(
			        HOUR(hora_inicio_fin[hora_inicio]),
			        MINUTE(hora_inicio_fin[hora_inicio]),
			        SECOND(hora_inicio_fin[hora_inicio])
			    )
			
			VAR FinOriginal =
			    TIME(
			        HOUR(hora_inicio_fin[hora_fin]),
			        MINUTE(hora_inicio_fin[hora_fin]),
			        SECOND(hora_inicio_fin[hora_fin])
			    )
			
			VAR Fin =
			    IF(FinOriginal < Inicio, FinOriginal + 1, FinOriginal)
			
			VAR Extra = hora_inicio_fin[Extra]
			
			VAR Inicio50 = TIME(18,0,0)
			VAR Fin50 = TIME(23,59,59)
			
			VAR InicioCalc = MAX(Inicio, Inicio50)
			VAR FinCalc = MIN(Fin, Fin50)
			
			RETURN
			IF(
			    FinCalc > InicioCalc && NOT ( Extra IN { "Feriado", "Extra" } ),
			    (FinCalc - InicioCalc) * 1440,
			    0
			)
		displayFolder: Totales y Formato
		lineageTag: 00faf570-44c9-4b93-adde-91d242fab6e5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Minutos extra con recargo al 100%, correspondientes a jornadas Extra, Feriado o tramo Extra Temprano. Base de las medidas HorasExtra100_h_mm.
	column Minutos100 =
			
			VAR Inicio =
			    TIME(
			        HOUR(hora_inicio_fin[hora_inicio]),
			        MINUTE(hora_inicio_fin[hora_inicio]),
			        SECOND(hora_inicio_fin[hora_inicio])
			    )
			
			VAR Fin =
			    TIME(
			        HOUR(hora_inicio_fin[hora_fin]),
			        MINUTE(hora_inicio_fin[hora_fin]),
			        SECOND(hora_inicio_fin[hora_fin])
			    )
			
			VAR Extra = hora_inicio_fin[Extra]
			
			-- Rango 100
			VAR Inicio100 = TIME(0,0,0)
			VAR Fin100 = TIME(9,0,0)
			
			-- Cálculo solo para rango 100
			VAR InicioCalc = MAX(Inicio, Inicio100)
			VAR FinCalc = MIN(Fin, Fin100)
			
			RETURN
			IF (
			    Extra IN { "Feriado", "Extra" },
			    -- En feriado se cuentan TODOS los minutos
			    MAX( (Fin - Inicio) * 1440, 0 ),
			    -- Caso normal: solo de 00:00 a 09:00
			    IF (
			        FinCalc > InicioCalc,
			        (FinCalc - InicioCalc) * 1440,
			        0
			    )
			)
		displayFolder: Totales y Formato
		lineageTag: 6add59dc-a3c1-4607-b662-1c8af2a722b7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Identificador del proyecto asociado al registro (si aplica).
	column proyecto_id
		dataType: int64
		formatString: 0
		lineageTag: fb8397b3-df47-4db2-b0e8-8442a72cf0eb
		summarizeBy: sum
		sourceColumn: proyecto_id

		annotation SummarizationSetBy = Automatic

	/// Detalle o descripción de la actividad registrada.
	column detalle
		dataType: string
		lineageTag: 76839acc-06f2-4a22-be31-91cd501a756d
		summarizeBy: none
		sourceColumn: detalle

		annotation SummarizationSetBy = Automatic

	partition hora_inicio_fin = m
		mode: import
		source =
				let
				    Origen = Odbc.Query("dsn=PostgreSQL35W", "SELECT *#(lf)FROM public.mv_fichas_rangos_detalle;"),
				    #"Columnas quitadas" = Table.RemoveColumns(Origen,{"tipo_dia", "horas_utilizadas", "tipo_ficha", "id_original", "nombreContacto", "nombre_dia"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

